### ISSUE TITLE
More issues with new features

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#25]
After you resume a tab that was created with the new "dont load new background tabs" if you click on it before it loads the tab will not load when you click on it. The url will stay as about:blank and the title of the tab will be the url

If a tab is loading the option to suspend it is replaced with resume tab even though it's not suspended

**Comment by piroor** [comment]
Latest development build seems to work correctly for me. Is this expired?

**Comment by rayman89** [comment]
This is fixed but there is an Issue with the try to cache option  #52
