### ISSUE TITLE
Issue with protecting tabs

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#29]
If you protect a tab but you are not focused on that tab when you protect it then the tab gets suspended.

**Comment by piroor** [comment]
On my Firefox 44 they seem to work correctly: protected tabs are not suspended automatically.

 * Suspend Tab 0.2.2016012900a182849
 * Tab Mix Plus 0.4.2.0

Is this issue expired or already fixed?

**Comment by rayman89** [comment]
This is fixed on the new release.
