### ISSUE TITLE
Suspended tabs sometimes return as e10s tabs

### ISSUE THREAD

**Issue by SoWhy** [piroor/suspendtab#30]
I updated to Firefox Beta v. 33 and now some tabs' titles are randomly underlined. Those tabs cannot be closed anymore. Sometimes the tab can't even be accessed anymore but that too is random. 

I read on various sites that underlining means e10s is enabled but I checked about:config and both browser.tabs.remote and browser.tabs.remote.autostart are set to false.

After someone told me it might be related to this extension, I disabled it and the problem went away, so I think it's a bug in this extension

**Comment by piroor** [comment]
Seems to be expired.
