### ISSUE TITLE
Blank Tabs bugs and Issues with Protected tabs

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#33]
After you resume a tab that was created with the new "dont load new background tabs" if you click on it before it loads or if there is an error loading the tab like it takes more time than needed or if you suddenly loose internet connection the tab will never load when you click on it. The url will stay as about:blank and the title of the tab will be the url.

If you have tabs that you never actually loaded cause of the new feature then when you merge windows those tabs become just blank.

If you protect a tab but you are not focused on that tab when you protect it then the tab gets suspended.

Also If a tab is loading the option to suspend it is replaced with resume tab even though it's not suspended

This issue is still present also https://github.com/piroor/suspendtab/issues/12

**Comment by piroor** [comment]
Merging of windows with protected/unprotected-unsuspended/unprotected-suspended tabs is successfully performed for me with the latest development build on Firefox 44 + TMP. This seems to be expired and already fixed.

**Comment by rayman89** [comment]
It's fixed.
