### ISSUE TITLE
Visual changes with expanding/collapsing the tree that has just autosuspended branch/tab

### ISSUE THREAD

**Issue by seafox** [piroor/suspendtab#35]
Suspend Tab 0.2.2014100200a144152. Tree Style Tab 0.14.2014051101.
For instance, open a branch with a child tab, then collapse its parent by pressing V arrow (that click will BTW unnecessarily auto-load this parent!), then select some other branch outside the collapsed parent. On suspended tab timeout, the suspended tab become visible as the branch containing this tab UNEXPECTEDLY expands. TST has automatical collapse/expand boxes cleared.

**Comment by piroor** [comment]
Seems to be expired. This doesn't happen on my Firefox 44, TST 0.16.2016012800a214113, and Suspend Tab 0.2.2016012900a171444.
