### ISSUE TITLE
Version Detection code is broken (and workaround to fix this for Palemoon 25)

### ISSUE THREAD

**Issue by Dwedit** [piroor/suspendtab#39]
This version detection code doesn't work in Palemoon 25.1.0:
file: suspendtab.js"

Cu.import('resource://gre/modules/Services.jsm');
if (Services.vc.compare(Services.appinfo.version, '25.0') < 0) {
	load('suspendtab-internal-24');
}
else {
	load('suspendtab-internal');
}

I don't understand what this code does, but if I comment out the conditional, and force it to always load the "24" file instead of the other one, the extension works perfectly in Palemoon 25.

**Comment by piroor** [comment]
Expired.
