### ISSUE TITLE
Don't load background tabs Issue

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#40]
Since the last update of firefox 36 and on firefox 37 the feature dont load background tabs is not working consistently. Like 40% of the time when you open a background tab the tab will load normally.

**Comment by piroor** [comment]
Does the latest development build work correctly? On recent changes I've realized that old implementation (on Firefox 38-40) possibly fail to suspend tabs and the new TabStateFlusher introduced at https://bugzilla.mozilla.org/show_bug.cgi?id=1162871 solves the issue. Now, on Firefox 41 and later, Suspend Tab uses TabStateFlusher's asynchronous feature to suspend tabs safely.

**Comment by rayman89** [comment]
On the new version this is fixed I also tested the "try to cache" option as well and both work properly.
