### ISSUE TITLE
October 11th build not working 

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#42]
As far as I tested the October 11th build does not work at all (menu options do not display auto unload does not happen the do not load background tabs doesn't work either) I tested it on clean profiles on version 42 and 40.

If possible when you fix it could you add the option to the do not load background tabs to actually load a bit the title and then instantly auto unload cause never loaded tabs tend to generate issues with other add-ons.

Also would be nice to get and import/export function for the whitelist.

**Comment by piroor** [comment]
Expired by #43
