### ISSUE TITLE
Request: Unload tabs after they have loaded

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#44]
Could you add an option for the do not load background tabs that actually lets them load but as soon as the title is loaded it unloads? This would be useful to be able to see the what the tab is and there are some add-ons that have issues with this "never loaded" tabs so that will be a simple workaround for that. Thanks for your time.

**Comment by piroor** [comment]
Done by 7ca11d35cf4112c6a85a667321487566182f624a.

**Comment by rayman89** [comment]
Thanks a lot.
