### ISSUE TITLE
REQUEST: menu entries on right mouse click

### ISSUE THREAD

**Issue by mausalimi** [piroor/suspendtab#46]
hi,

wow, newest suspendtab now works here, the one before dis not. thanks for this!

but i have a request: it would help (me) a lot, if there was a menu entry for suspending the current tab not only in the tab menu, but also when just right clicking on the page.

i have TST vertical with autoshrink and small tab height, it's a bit of a hassle to move the mouse over the tab to get the tab menu.

thanks for reading. :)

**Comment by piroor** [comment]
Done by a7c1cb93642a61f707653bffbaf82c4e95313448.

**Comment by mausalimi** [comment]
great, it works. i had a feeling this isn't too much work.

btw, i did translate it to german, if you're interested.
most likely not the best translation ever, but maybe better than nothing.


[de-DE.zip](https://github.com/piroor/suspendtab/files/108728/de-DE.zip)
