### ISSUE TITLE
try to cache the content issue

### ISSUE THREAD

**Issue by rayman89** [piroor/suspendtab#52]
If you enable the "try to cache" option and you click on the tab before it finishes loading the page will either become a blank tab with no url at all or the page will look blank with the url on the address bar and get suspended while you are looking at it so you have to switch to an other time and back to make it load or make it load the address by pressing enter or the go button on the address bar.

**Comment by piroor** [comment]
b10cc2522c1459e75c2a0135d54838a75f439e6b should fix this.

**Comment by rayman89** [comment]
It's fixed.
