### ISSUE TITLE
174bc8a doesn't work with exceptions

### ISSUE THREAD

**Issue by mausalimi** [piroor/suspendtab#53]
it seems, [174bc8a ](https://github.com/piroor/suspendtab/commit/174bc8aea95579fb6e46115e88541dc06fb9d861)can't handle the exceptions list?

or is this by design?

btw, the newest german translation (not great work, but something to start with at least...), if interested:

[suspendtab 30-Jan-2016 01.37_DE.xpi.zip](https://github.com/piroor/suspendtab/files/110415/suspendtab.30-Jan-2016.01.37_DE.xpi.zip)

**Comment by piroor** [comment]
By recent changes the exception list is now applied for the feature.

**Comment by piroor** [comment]
Oops, I forgot to response about the locale. Could you send it as a pull request instead of an archive?
