### ISSUE TITLE
1.0.2016020401 does not give any sign of presence on 38.6.1

### ISSUE THREAD

**Issue by satnatantas** [piroor/suspendtab#55]
It is listed in extensions list and options button is available but nothing more - no tab menu, no page menu, no tab suspension.

Same with clean profile.

**Comment by satnatantas** [comment]
Just the same with 1.0.2016031500a191747

**Comment by piroor** [comment]
How about on Firefox 45? If it works on Firefox 45, I hope to drop support for outdated versions. (I know Firefox 38ESR is still supported, but for a personal author both versions of ESRs are hard to be supported.)

**Comment by satnatantas** [comment]
Yes, seems to work on 45 with same profile.
