### ISSUE TITLE
Replace __SS* in code

### ISSUE THREAD

**Issue by trlkly** [piroor/suspendtab#6]
Per Mozilla [bug 874381](https://bugzilla.mozilla.org/show_bug.cgi?id=874381), SessionStore fields, those starting with __SS, are due to be removed, starting with Firefox 25.0. The uses of these undocumented features seem to be quite small, so I would expect it would be too hard to replace.

See the depends and blockers on that bug to see how Mozilla replaced them in their code. In general, they used WeakMap in internal methods.

**Comment by piroor** [comment]
Expired.
