### ISSUE TITLE
Option "Suspend other tab" on context menu isn't hidden

### ISSUE THREAD

**Issue by SG5** [piroor/suspendtab#61]
Firefox DE 48.0a2 (2016-05-10)
Another options are hidden without problem

![suspend-tab](https://cloud.githubusercontent.com/assets/3931761/15180906/efd40adc-178c-11e6-9058-7800241b5cf5.jpg)

**Comment by i-cant-git** [comment]
Yeah I can confirm, I have this issue too. All items are unchecked on Options/Menu dialog.

**Comment by piroor** [comment]
This was fixed by #57 (not released yet)

**Comment by i-cant-git** [comment]
When will be released?
