### ISSUE TITLE
Can't hide "Suspend Other Tabs" context menu entry

### ISSUE THREAD

**Issue by ssokolow** [piroor/suspendtab#63]
I try to keep my page context menu clean and strictly focused on content-related actions, so I've disabled all of the Suspend Tab entries in it (leaving them visible in the tab bar context menu).

However, despite having all page context menu entries unchecked in settings, "Suspend Other Tabs" remains visible below "ScrapBook ▸"  in the page context menu.

**Comment by vzvu3k6k** [comment]
The patch to fix this problem has been merged, but a fixed version is not released yet. (See [#61](https://github.com/piroor/suspendtab/issues/61#issuecomment-222357046).)

**Comment by vzvu3k6k** [comment]
A fixed version has been released as 1.0.2016061501.

**Comment by piroor** [comment]
I forgot to close this.
