### ISSUE TITLE
Suspend Tab 1.0.2016061501 not compatible with e10s with Tab Mix Plus 0.5.0.5pre.180718a1: restored tabs have titles but neither addresses, nor content

### ISSUE THREAD

**Issue by grahamperrin** [piroor/suspendtab#77]
### Background

Spun off from https://www.reddit.com/comments/90x5n9/-/e2xkvxe/

### Issue

With Suspend Tab enabled, Tab Mix Plus restoration of sessions results in this (for example): 

![2018-07-28 13 09 44 mozilla pastebin - collaborative debugging tool - waterfox](https://user-images.githubusercontent.com/192271/43356532-09f944ae-926a-11e8-9210-5dd3f3eb4afa.png)

Not all tabs are affected, but the symptom is highly reproducible. 

### Workarounds

Either: 

1. disable multi-process Waterfox; **or**
2. disable Suspend Tab.

Not reproducible with [Auto Unload Tab](https://addons.mozilla.org/addon/auto-unload-tab/) 0.9.1.5 in lieu of Suspend Tab. 

### Test environment

[Tab Mix Plus](https://addons.mozilla.org/addon/tab-mix-plus/) 0.5.0.5pre.180718a1 from http://tabmixplus.org/support/viewtopic.php?t=1

[Waterfox](https://www.waterfoxproject.org/) 56.2.2 on FreeBSD-CURRENT

```text
$ pkg info waterfox | grep Version
Version        : 56.2.2
$ date ; uname -v
Sat 28 Jul 2018 07:44:08 BST
FreeBSD 12.0-CURRENT #7 r336136: Tue Jul 10 03:01:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
$ 
```

**Comment by piroor** [comment]
Sorry, I maintained this project just for Firefox and forked versions of Firefox are not supported by me. if you like, fork this project and maintain for future version of those forked Firefox like Tree Style Tab for Pale Moon: https://github.com/oinkin/treestyletab

**Comment by grahamperrin** [comment]
Thanks for replying. Understood :+1:
