### ISSUE TITLE
Feature Request: Option to use the number of tabs instead of just a timer

### ISSUE THREAD

**Issue by trlkly** [piroor/suspendtab#8]
This is something I saw requested on the addon review page, and I think it makes sense. A user may wish to automatically unload the Xth last used tab. Say I have it set to 10 tabs, and have 10 tabs open. Then I open an 11th. SuspendTab would then automatically unload the 11th most recently clicked on tag.

This would be fairly easy to accomplish using a sort of queue that keeps track of the X most recently clicked on tabs, Any time a tab is clicked, it is removed from the queue and added back at the front. And any time you get X+1 tabs, the tab on the bottom of the queue would be unloaded, then deleted from the queue.

This could also be allowed concurrently with the timer-based options. Just have the queue-based unload fail silently if the tab is already unloaded, and then still remove it form the queue. Or, if you want, have any unloaded tab automatically removed from the queue--either works.

**Comment by piroor** [comment]
Done by 174bc8aea95579fb6e46115e88541dc06fb9d861
